[package]
name = "ashv2"
description = "Implementation of the Asynchronous Serial Host (ASH) protocol by Silicon Labs."
license = "MIT"
repository = "https://github.com/PaulmannLighting/ashv2"
keywords = ["ASH", "async", "serial", "host"]
categories = ["network-programming"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
itertools = "0.11.0"
log = "0.4.20"
num-derive = "0.4.1"
num-traits = "0.2.17"
serialport = "4.2.2"
strum = { version = "0.25.0", features = ["derive"] }
