mod ash_read;
mod ash_write;
mod baud_rate;
mod buffer;
mod code;
pub mod error;
pub mod frame;
pub mod packet;
pub mod protocol;
mod serial_port;
mod util;

use code::Code;
use crc::{Crc, CRC_16_IBM_3740};
pub use error::{Error, FrameError};
pub const CRC: Crc<u16> = Crc::<u16>::new(&CRC_16_IBM_3740);
pub use ash_read::AshRead;
pub use ash_write::AshWrite;
pub use baud_rate::BaudRate;
pub use protocol::{Event, HandleResult, Host, Response};
pub use serial_port::open;
